version: '3'
services:


  db:
    ports:
      - 5432:5432

  graphql:
    ports:
      - 5433:5433

  app:
    container_name: mobydq-app
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - './app:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 80:3000
    command: "npm test -- --coverage"